language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - composer install --prefer-source --dev
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --coverage-text
  - phpcs --standard=psr2 ./lib