language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - php composer.phar require symfony/http-foundation:${SYMFONY_VERSION}
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text

env:
  - SYMFONY_VERSION="~2.0"
  - SYMFONY_VERSION="2.0.*"
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"
